---
sudo: false

language: ruby

cache: bundler

rvm:
  - 2.3.3
  - 2.4.2
  - 2.5.7
  - 2.6.5
  - 2.7.1

before_install: gem install bundler

gemfile:
  - Gemfile
bundler_args: "--without development --deployment"

install:
  - bundle install

script:
  - ruby -e "if RUBY_VERSION >= '2.7'; system('bundle exec rubocop --fail-level=W'); end"
  - bundle exec rspec spec --exclude-pattern "spec/r2-oas/tasks/tool_spec.rb,spec/r2-oas/tool/paths/stats_spec.rb"
